service: ms-${self:custom.serviceName}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: 'us-east-1'
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - ses:SendTemplatedEmail
        - ses:SendBulkTemplatedEmail
      Resource: arn:aws:ses:*
  apiGateway:
    restApiId: 411z282v69
    restApiRootResourceId: 4efcqfttn0

custom:
  esbuild:
    external:
      - pg-native
  serviceName: emails
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/4-framework/functions
functions:
  sendMail:
    handler: ${self:custom.funcDir}/sendMail.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: post
          cors:
            origin: '*'
            headers: '*'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
