service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

custom:
  esbuild:
    external:
      - pg-native
  serviceName: emails
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
